instrucciones de desarrollo
onefacture/sat-facturacion-experiment pull request #1
Opened 2019-11-19 21:21 UTC by categulario

pa'que le sea más fácil a la gente

2019-11-19 21:52 UTC, ricaralan requested changes
Gracias por el aporte, podrías cambiar los detalles? 🙏🙏🙏🙏

2019-11-19 21:52 UTC, ricaralan commented on README.md
> +* `npm run start`
Podrías sustituirlo para varías lineas? 🙏

```
npm i
npm start
```

2019-11-19 21:52 UTC, ricaralan commented on README.md
> +* No arranca en linux
Aquí podrías ponerlo en la misma línea? 🙏

Si no arranca en linux — Añadir al comando `start` de `package.json` un `--no-sandbox` al final. Según [esto](https://github.com/electron/electron/issues/17972) es un problema lo del sandbox.

2019-11-20 10:14 UTC, categulario commented on README.md
> +* No arranca en linux
la idea de que esté así es dar espacio y formato para más cosas que podrían fallar y sus formas de corregir, un poco pensando en la legibilidad y la organización

2019-11-20 10:18 UTC, categulario commented on README.md
> +* `npm run start`
listo, ya lo puse en un bloque. La razón por la que uso la versión larga de los comandos es que si se es nuevo es más fácil entender qué pasa o se tiene una versión sin menos trucos y magia de lo que está pasando, por ejemplo saber qué significa `i` puede ser difuso pero entender `install` es fácil. De manera similar con el `run`, la única razón por la que no es necesario es porque `start` está registrado como un atajo en npm, pero si fuera un comando propio el `run` sería necesario, lo cual puede ser confuso. Entonces le doy prioridad a la claridad.

de todas formas si ya se tiene un nivel avanzado de node hacer el cambio al momento de escribirlos es trivial.

2019-11-20 10:32 UTC, ricaralan commented on README.md
> +* No arranca en linux
Concuerdo contigo. Creo que no me explique bien 😅. La idea era dejarlo en una línea para poder añadir más elementos a la lista de errores.

* **LINUX-ELECTRON SANDBOX**: Solución ... `--no-sandbox`
* TIPO ERROR: Solución
* TIPO ERROR: Solución

2019-11-20 10:39 UTC, categulario commented on README.md
> +* No arranca en linux
eso lo veo, solo que las soluciones podrían llegar a ser de más de un párrafo

2019-11-20 10:39 UTC, categulario commented on README.md
> +* No arranca en linux
pero también creo que es irrelevante a esta altura

2019-11-20 10:41 UTC, merged